stages:
  - build
  - test

variables:
  THREADS: 9
  GIT_SUBMODULE_STRATEGY: recursive

nix-build:
  stage: build
  # Use 2.3.12 due to https://github.com/NixOS/nix/issues/5797
  image: nixos/nix:2.3.12
  before_script:
    - |
      if [ -e ./cache.nar ]; then
          nix-store --import < ./cache.nar || true
      fi
    - nix-env -iA git -f '<nixpkgs>'
    - nix-env -iA cachix -f '<nixpkgs>'
    - cachix use trec-car-tools
    - cachix authtoken $CACHIX_AUTH_TOKEN
    - nix-build '<nixpkgs>' -A hello | cachix push trec-car-tools
  script:
    - nix-build . -A env --cores 1 -j $THREADS | cachix push trec-car-tools
    - nix-build . -A binaries --cores 1 -j $THREADS | cachix push trec-car-tools
    - nix-store --export $(nix-store -qR ./result) > ./cache.nar
  cache:
    key: nix
    paths:
      - ./cache.nar

.build-static:
  image: alpine:3.15
  allow_failure: true
  variables:
    EXEC_NAME: TODO
    BOOTSTRAP_HASKELL_GHC_VERSION: 9.2.1
  stage: build
  before_script:
    - apk add curl xz xz-dev icu icu-dev icu-static zlib-static zlib-dev
        binutils-gold curl gcc gmp-dev libc-dev libffi-dev make
        musl-dev ncurses-dev perl tar xz git
        leveldb leveldb-dev kyotocabinet kyotocabinet-dev bzip2 bzip2-dev
    - curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
    - source /root/.ghcup/env
    - ghc --version
    - cp cabal.project.local.ghc-9.2 cabal.project.local
    - cabal update
    - rm -Rf out
    - rm -Rf result
  script:
    - |
      cat >>cabal.project.local <<EOF
      store-dir: /trec-car-tools-haskell/.cabal-store
      package *
        ghc-options: -optl=-static
        executable-static: True
        executable-dynamic: False
        shared: False
        static: True
      EOF
    - cabal build ${EXEC_NAME/#/exe:}
    - rm -Rf result; mkdir -p result
    - |
      for i in $EXEC_NAME; do
        cp $(cabal list --store-dir=$(pwd)/.cabal-store exe:$i) result
      done
    - ls -lh result
    - ls -lh out 
  cache:
    paths:
      - .cabal-store
  artifacts:
    expire_in: 8 weeks
    paths:
      - result

.static-trec-car-build-toc:
  extends: .build-static
  variables:
    EXEC_NAME: trec-car-dump trec-car-build-toc trec-car-trec-run-filter trec-car-trec-run-modify trec-car-qrels-modify trec-car-cat
